### ISSUE TITLE
Login Akses Pengembang

### ISSUE THREAD

**Issue by ekohendratno** [eraporsmk/erapor7#1]
Apa saja login akses untuk pengembangan aplikasi eraport ini? Terutama untuk testing
seperti login admin default dan lainnya.

Karena tertarik untuk mengembangkan eraport ini kedepannya

**Comment by eraporsmk** [comment]
Akses login menggunakan akses dapodik.
Aplikasi ini khusus untuk SMK saja, tidak untuk umum.

Terima Kasih
