### ISSUE TITLE
detail malih (mapel pilihan) milik walas rombel malih tdk muncul

### ISSUE THREAD

**Issue by dwi-adhi-soegiarto** [eraporsmk/erapor7#101]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: Windows 11 Pro
2. Versi Aplikasi: 7.0.5
3. Versi Database: 6.0.2

Walas mapel pilihan (malih) ketika klik detail tdk muncul apapaun, hanya tombol OK dan erapor reload
nama walas juga tdk muncul di rombel malih (lihat ss)
![error erapor](https://github.com/eraporsmk/erapor7/assets/139864442/464bc7e6-56bd-4524-b944-455800db5f68)

**Comment by masadi** [comment]
proses update kemungkinan tidak sempurna
pastikan command ```composer update``` sukses tanpa ada error
