### ISSUE TITLE
Tidak Sesuai Antara Nilai Projek P5 yg diinput dengan Hasil Cetak Rapor P5

### ISSUE THREAD

**Issue by rifqi-anshory** [eraporsmk/erapor7#102]
Aplikasi yang sedang dipakai:

Operating System: Windows 10 Pro
Versi Aplikasi: 7.0.5
Versi Database: 6.0.2

Mau menanyakan tentang rapor p5. Ada beberapa fasilitator P5 yg menemui ketidak sesuaian antara nilai projek yg dimasukkan dengan di bagian cetak rapor p5. 
Misal di bagian Nilai Projek sudah dipilih Sedang Berkembang, tetapi di cetak rapor yg muncul Berkembang sesuai harapan.

![1](https://github.com/eraporsmk/erapor7/assets/172477482/edc2d59b-483b-4302-8665-6c5d262ff2b6)
.
![2](https://github.com/eraporsmk/erapor7/assets/172477482/615749c8-98b7-4341-8adc-49fba2b8ecdf)

**Comment by masadi** [comment]
Silahkan update kembali aplikasinya:
- git pull
- composer update
- php artisan erapor:update
