### ISSUE TITLE
Problem saat install ke hosting

### ISSUE THREAD

**Issue by elasghar** [eraporsmk/erapor7#103]
Mohon dibantu masalah berikut ini:

saat menjalankan script ke hosting online:
`php artisan migrate`

![gambar](https://github.com/eraporsmk/erapor7/assets/133491029/43ae9ed9-2a8d-48fd-9240-9f6eeca9452d)

Mohon pencerahannya, terimakasih banyak.

**Comment by elasghar** [comment]
> > Mohon dibantu masalah berikut ini:
> > saat menjalankan script: `php artisan migrate`
> > ![gambar](https://private-user-images.githubusercontent.com/133491029/339043632-43ae9ed9-2a8d-48fd-9240-9f6eeca9452d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzQ2MDgsIm5iZiI6MTcxODIzNDMwOCwicGF0aCI6Ii8xMzM0OTEwMjkvMzM5MDQzNjMyLTQzYWU5ZWQ5LTJhOGQtNDhmZC05MjQwLTlmNmVlY2E5NDUyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQyMzE4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWJlY2E5MDliMTI0ZDgyNWVjMjAxOWJkMTlmNWI5Y2I0YWNiY2I5NTgyZjFiZDVlZTY0ZWU3M2E3NDQ0ZTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oVv77a2F_sCsoCDNbtD-oVe9kcdALOD09PFHnNEqmtM)
> > Mohon pencerahannya, terimakasih banyak.
> 
> kalau di localhost biasanya dikarenakan service eraporsmkdb belum berjalan.

Kalo di localhost alhamdulillah aman, om.
Ini pas mau tak online ke hosting yang gak bisa.

**Comment by enjangjahrudin** [comment]
> > > > Mohon dibantu masalah berikut ini:
> > > > saat menjalankan script: `php artisan migrate`
> > > > ![gambar](https://private-user-images.githubusercontent.com/133491029/339043632-43ae9ed9-2a8d-48fd-9240-9f6eeca9452d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzQ2MDgsIm5iZiI6MTcxODIzNDMwOCwicGF0aCI6Ii8xMzM0OTEwMjkvMzM5MDQzNjMyLTQzYWU5ZWQ5LTJhOGQtNDhmZC05MjQwLTlmNmVlY2E5NDUyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQyMzE4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWJlY2E5MDliMTI0ZDgyNWVjMjAxOWJkMTlmNWI5Y2I0YWNiY2I5NTgyZjFiZDVlZTY0ZWU3M2E3NDQ0ZTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oVv77a2F_sCsoCDNbtD-oVe9kcdALOD09PFHnNEqmtM)
> > > > Mohon pencerahannya, terimakasih banyak.
> > > 
> > > 
> > > kalau di localhost biasanya dikarenakan service eraporsmkdb belum berjalan.
> > 
> > 
> > Kalo di localhost alhamdulillah aman, om. Ini pas mau tak online ke hosting yang gak bisa.
> 
> coba di cek saja apakah service-nya jalan atau tdk

caranya bagaimana ?

**Comment by enjangjahrudin** [comment]
> Mohon dibantu masalah berikut ini:
> 
> saat menjalankan script ke hosting online: `php artisan migrate`
> 
> ![gambar](https://private-user-images.githubusercontent.com/133491029/339043632-43ae9ed9-2a8d-48fd-9240-9f6eeca9452d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzM4ODIsIm5iZiI6MTcxODM3MzU4MiwicGF0aCI6Ii8xMzM0OTEwMjkvMzM5MDQzNjMyLTQzYWU5ZWQ5LTJhOGQtNDhmZC05MjQwLTlmNmVlY2E5NDUyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxMzU5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDM0MzY0MTAxYWUyZmNlNjk2ZTg0Y2FiMmUxMWY1OGFmYzIzZDkyZThlNGZkNTJhMDNjYThiNzQ5YjU0OTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c9Pansvkf_1AVDD8AaQPpLG8zd2ECr-kfoy02pvyi3g)
> 
> Mohon pencerahannya, terimakasih banyak.

Masalah yang sama. Apakah sudah ada solusinya ?

**Comment by elasghar** [comment]
> > > > > Mohon dibantu masalah berikut ini:
> > > > > saat menjalankan script: `php artisan migrate`
> > > > > ![gambar](https://private-user-images.githubusercontent.com/133491029/339043632-43ae9ed9-2a8d-48fd-9240-9f6eeca9452d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzQ2MDgsIm5iZiI6MTcxODIzNDMwOCwicGF0aCI6Ii8xMzM0OTEwMjkvMzM5MDQzNjMyLTQzYWU5ZWQ5LTJhOGQtNDhmZC05MjQwLTlmNmVlY2E5NDUyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQyMzE4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWJlY2E5MDliMTI0ZDgyNWVjMjAxOWJkMTlmNWI5Y2I0YWNiY2I5NTgyZjFiZDVlZTY0ZWU3M2E3NDQ0ZTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oVv77a2F_sCsoCDNbtD-oVe9kcdALOD09PFHnNEqmtM)
> > > > > Mohon pencerahannya, terimakasih banyak.
> > > > 
> > > > 
> > > > kalau di localhost biasanya dikarenakan service eraporsmkdb belum berjalan.
> > > 
> > > 
> > > Kalo di localhost alhamdulillah aman, om. Ini pas mau tak online ke hosting yang gak bisa.
> > 
> > 
> > coba di cek saja apakah service-nya jalan atau tdk
> 
> caranya bagaimana ?

Belum dapet, om... :(

**Comment by masadi** [comment]
Coba tanyakan ke CS hostingnya, cara koneksi laravel ke database postgres

Pada Jum, 14 Jun 2024, 21.33, almstf ***@***.***> menulis:
