### ISSUE TITLE
Hak akses pengguna hilang

### ISSUE THREAD

**Issue by arifrahman26** [eraporsmk/erapor7#104]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: windows 10
2. Versi Aplikasi: 7.0.4
3. Versi Database: 6.0.0
awalnya saya ingin menambahkan hak akses pembina ekskul tapi tidak ada fasilitas yang bisa digunakan. kemudian saya klik atur ulang akses pengguna PTK namun yang terjadi malah hak akses dari guru-guru hilang hanya tersisa 2 guru wali kelas XI. mohon solusinya
![akses pengguna hilang](https://github.com/eraporsmk/erapor7/assets/145173301/cd69cce0-b072-438b-8520-1c59c84b5832)

**Comment by arifrahman26** [comment]
sudah saya coba tapi belum ada hasilnya

**Comment by masadi** [comment]
> sudah saya coba tapi belum ada hasilnya

pastikan versi sudah berubah menjadi v7.0.5
