### ISSUE TITLE
p5 akses akun tidak bisa muncull

### ISSUE THREAD

**Issue by ferismkn4madiun** [eraporsmk/erapor7#106]
status sudah singkron dapodik, dan singkron eraport 
dan sudah di atur pengguna 
tp menu akun p5 tidak mucul
![p5](https://github.com/eraporsmk/erapor7/assets/127709535/33e0c0d5-a61c-4164-93e1-6c58f2ffb410)

**Comment by xenoncoder** [comment]
Sudah pilih tema di dapodik?

**Comment by ferismkn4madiun** [comment]
sudah kami lakukan semua cara pak

**Comment by xenoncoder** [comment]
Terakhir sinkron kapan? Kalau baru beberapa jam gak bisa pak, harus nunggu dulu
