### ISSUE TITLE
Nilai Matapelajara Pilihan di Ledger Tidak Muncul

### ISSUE THREAD

**Issue by shinataputra** [eraporsmk/erapor7#109]
Aplikasi yang sedang dipakai: 
1. Operating System: Windows 11
2. Versi Aplikasi: 7.0.5
3. Versi Database: 6.0.3

![lapor bug 2 erapor](https://github.com/eraporsmk/erapor7/assets/71615861/31a3be10-5342-4207-9546-3d73a27cc0a1)

nilai mapel pilihan tidak muncul di ledger baik di akun wali kelas maupun di akun kurikulum tapi muncul di detail mapel dan cetak rapor, ini terjadi di beberapa kelas tidak semua kelas

**Comment by masadi** [comment]
nilai mapel pilihan hanya bisa di akses di walas rombel pilihan
