### ISSUE TITLE
SETELAH UPDATE ERAPOR TAHUN PELAJARAN KOSONG

### ISSUE THREAD

**Issue by WARDI-NURYANTO** [eraporsmk/erapor7#110]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: WINDOW 11
2. Versi Aplikasi: 7.0.5
3. Versi Database:6.0.2

![2024-06-26_13h04_17](https://github.com/eraporsmk/erapor7/assets/119034175/2e2bcfa4-8ee3-49c3-b330-c5f753d8d67b)

**Comment by masadi** [comment]
Silahkan update kembali aplikasinya:
- git pull
- composer update
- php artisan erapor:update
