### ISSUE TITLE
Cetak ulang cover Halaman Depan erorr 500

### ISSUE THREAD

**Issue by novaulul** [eraporsmk/erapor7#111]
Cetak ulang halaman depan rapor keluar erorr 500 padahal Cetak nilai Rapor Lancar2 aja
bagaimana solusinya ?

#Menggunakan VPS Linux ubuntu 20.04 LTS dan domain sch.id
#Versi erapor : 7.0.5
#versi database: 6.0.4

<img width="558" alt="cetak" src="https://github.com/eraporsmk/erapor7/assets/96112145/6948321c-72b2-4c75-84f6-5281478a5d27">

**Comment by masadi** [comment]
Silahkan update kembali aplikasinya:
- git pull
- composer update
- php artisan erapor:update

jika masih tetep sama, silahkan hubungi tim helpdesk untuk di remote
