### ISSUE TITLE
Proses Sinkron bermasalah

### ISSUE THREAD

**Issue by Kunyank** [eraporsmk/erapor7#112]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: win 11
2. Versi Aplikasi: 7.0.5
3. Versi Database: 6.0.2
![WhatsApp Image 2024-06-29 at 13 01 32_47a80064 (2)](https://github.com/eraporsmk/erapor7/assets/120827421/3abdee9d-de58-45f4-a4eb-ec341e044b2f)

**Comment by masadi** [comment]
Silahkan update kembali aplikasinya:
- git pull
- composer update
- php artisan erapor:update
