### ISSUE TITLE
GAGAL KIRIM DATA ERAPOR SMK (ERROR 500! Undefined property: Illuminate\Http\Client\Response::$status)

### ISSUE THREAD

**Issue by smkptm** [eraporsmk/erapor7#113]
mohon bantu solusinya,,, mau kirim data erapor smk. tapi ga bisa terus keterangannya sesuai di gambar
Aplikasi yang sedang dipakai:
1. Operating System: WINDOWS 1O
2. Versi Aplikasi: 7.05
3. Versi Database:
![ERAPOR SMK EROR](https://github.com/eraporsmk/erapor7/assets/174221431/f51af92b-5b2a-4f67-9bcf-fc827cd3e703)

**Comment by masadi** [comment]
Silahkan update kembali aplikasinya:
- git pull
- composer update
- php artisan erapor:update
