### ISSUE TITLE
ERROR KIRIM DATA E-RAPOR

### ISSUE THREAD

**Issue by VitoFeranado** [eraporsmk/erapor7#114]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System:  Server VPS Almalinux
2. Versi Aplikasi: 7.0.5
3. Versi Database: 6.0.3

![image](https://github.com/eraporsmk/erapor7/assets/33283541/2a1e351c-1591-4ff2-ac3e-e8acb4d185df)

Setelah naik ke versi 7.0.5 error seperti ini ketika kirim data nilai erapor

**Comment by WARDI-NURYANTO** [comment]
Kasus sama Sekolah saya juga seperti in pak, Alhamdulillah sudah bisa sync kembali

**Comment by ebadrus** [comment]
> Kasus sama Sekolah saya juga seperti in pak, Alhamdulillah sudah bisa sync kembali nanti bisa sharing saja pak Tutorialnya dari saya

gimana pak solusinya?

**Comment by WARDI-NURYANTO** [comment]
Siappp nanti saya share langkahnya pak 🙏🏻

Pada Jum, 5 Jul 2024 09.55, ebadrus ***@***.***> menulis:

**Comment by WARDI-NURYANTO** [comment]
SOLVED KIRIM ERAPOR (ERROR 500)
1. Backup Erapor Data terakhir yg utama (folder database dan dataweb)
2. Uninstall erapor lama selesai
3. download erapor 7.0.5 di github erapor selesai
4. install erapor 7.0.5 tadi, selesai
5. buka aplikasi erapor 7.0.5, cuma registrasi saja, selesai
6. masuk ke service matikan eRaporSMKDB dan eRaporSMKWebSrv
7. Copy folder database hasil backup di atas dan paste di folder C:\eRaporSMK
8. Jalankan services eRaporSMKDB
9. Buka folder C:\eRaporSMK\updater
10.Klik kanan file update-erapor.bat dan pilih Run as Administrator
11.Klik kanan file symlink.bat dan pilih Run as Administrator
12.Selesai
pengembalian data erapor yang sudah diisi nilainya
13.masuk ke service lagi matikan eRaporSMKDB dan eRaporSMKWebSrv
14.Copy folder dataweb hasil backup di atas dan paste di folder C:\eRaporSMK
15.klik kanan refresh selesai
16.silahkan buka aplikasi erapornya dan login
