### ISSUE TITLE
setelah update terbaru menu kirim nilai ke dapodik kosong

### ISSUE THREAD

**Issue by WARDI-NURYANTO** [eraporsmk/erapor7#115]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: windows 10
2. Versi Aplikasi: 7.0.5
3. Versi Database: 6.0.4

![image](https://github.com/eraporsmk/erapor7/assets/119034175/5d6cea1b-e594-4830-b0a9-4f668b0b2fb8)

@masadi

**Comment by masadi** [comment]
Silahkan update kembali aplikasinya:
- git pull
- composer update
- php artisan erapor:update
