### ISSUE TITLE
compile ulang vuejs

### ISSUE THREAD

**Issue by arontama01** [eraporsmk/erapor7#118]
Aplikasi yang sedang dipakai:
1. Operating System: Arch Linux
2. Versi Aplikasi: terkini
3. Versi Database: terkini
4. NPM: terkini

mas, bisa diberi pencerahan bagaimana cara ubah publicPath di Vue js? Karena selalu terkendala npm error cross-env

harapan:
https:\\\localhost\erapor7

yang terjadi:
alamat selalu di https:\\\localhost dengan halaman putih loading

**Comment by masadi** [comment]
Cek pengaturan di webservernya pak, biasanya di sites-available

Pada Jum, 11 Okt 2024, 18.31, arontama01 ***@***.***> menulis:

**Comment by arontama01** [comment]
contoh kasus seperti ini mas, says punya beberapa aplikasi di server nya 

![20241013_150851-ezgif com-video-to-gif-converter(1)](https://github.com/user-attachments/assets/0e1d1890-3e2a-4f02-ad93-36ba0ccffa02)

harapan aplikasi bisa dibuka di alamat ini:
`https:\\localhost\erapor7`

yang terjadi:
alamat selalu di `https:\\localhost` dengan halaman putih loading

**Comment by masadi** [comment]
pake subdomain saja pak, jangan pake sub directory

**Comment by arontama01** [comment]
baik, terima kasih sarannya mas.
