### ISSUE TITLE
mengisi TP di kelas XI kejuruan untuk CP tidak muncul

### ISSUE THREAD

**Issue by merzakk** [eraporsmk/erapor7#15]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: 10
2. Versi Aplikasi: 7.0.2
3. Versi Database:6.0.0

Ketika mau memasukkan TP di kelas XI terutama kejuruan, Tiidak muncul CP nya.. padahal sudah di aktifkan

![e1](https://github.com/eraporsmk/erapor7/assets/119062563/b19d1b42-8393-43cf-881a-83dc09a89a39)

![e2](https://github.com/eraporsmk/erapor7/assets/119062563/28c4b229-5a18-4b25-95de-6950fcc27471)
di TP tidak muncul

![e3](https://github.com/eraporsmk/erapor7/assets/119062563/a9643327-f69b-4fb7-a974-2d9c700a0dc0)

**Comment by masadi** [comment]
Silahkan lakukan mapping rombel dulu di menu TP
