### ISSUE TITLE
mapel pilihan tidak bisa di simpan

### ISSUE THREAD

**Issue by smkronas** [eraporsmk/erapor7#3]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: Windows
2. Versi Aplikasi: 7.0.0
3. Versi Database: 6.0.0

ketika klik simpan muncul opsi tanpa ada keterangan
![Screenshot_7](https://github.com/eraporsmk/erapor7/assets/118788751/7e46920b-ef23-4069-a658-780182151bc4)

**Comment by eraporsmk** [comment]
Silahkan di update, sudah di perbaiki di #6766326

**Comment by smkronas** [comment]
terima kasih
