### ISSUE TITLE
Error migrate di php8.1

### ISSUE THREAD

**Issue by xsata1** [eraporsmk/erapor7#4]
could not find driver (SQL: select * from information_schema.tables where table_catalog = db_rapor7 and table_schema = public and table_name = migrations and table_type = 'BASE TABLE')

Gimana yapadahal pdo dll sudah di instal dan diaktifkan

**Comment by eraporsmk** [comment]
Silahkan cek kembali di phpinfo();
Apakah PDO pgsql sudah di aktif atau belum

![image](https://github.com/eraporsmk/erapor7/assets/53444184/7b8dfafd-d4fb-4a7c-a24e-5376b1c4e5c1)

**Comment by xsata1** [comment]
[image: image.png]
sudah itu kak


Pada tanggal Sel, 26 Sep 2023 pukul 12.22 eRaporSMK <
***@***.***> menulis:

**Comment by eraporsmk** [comment]
Balesnya langsung di github ya, kalo via email gak tampil gambarnya

Terima kasih

**Comment by xsata1** [comment]
[image: image.png]


Pada tanggal Sel, 26 Sep 2023 pukul 12.45 kurikulum smktengaran <
***@***.***> menulis:

**Comment by xsata1** [comment]
![Screenshot_1](https://github.com/eraporsmk/erapor7/assets/146055133/d98a929f-e3d8-47b0-8074-945044ec8283)

**Comment by xsata1** [comment]
sudah aktif tp tetep gak bsa

**Comment by eraporsmk** [comment]
php nya versi berapa?

**Comment by xsata1** [comment]
8.1

**Comment by eraporsmk** [comment]
di Command Line, coba ketik `php -m`
Apakah pdo pgsql ada?

**Comment by xsata1** [comment]
![image](https://github.com/eraporsmk/erapor7/assets/146055133/3fbda4cb-dda2-4862-bde4-04ce94ea2317)
sudah ada

**Comment by eraporsmk** [comment]
Belum ada pdo_pgsql. Silahkan di cek kembali

**Comment by xsata1** [comment]
kalau php-m nanti itu yang  php 8.2. padahal di vps phpnya sya set yang versi 8.1

**Comment by eraporsmk** [comment]
Silahkan hubungi CS VPS nya, untuk memastikan php-cli dan php-fpm yang digunakan sama.

Terima Kasih

**Comment by xsata1** [comment]
baik. terima kasih
