### ISSUE TITLE
Saat Cetak Erapor Tidak Muncul Matpel Pilihan

### ISSUE THREAD

**Issue by ibrahimwahyus** [eraporsmk/erapor7#43]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: Win 10
2. Versi Aplikasi: 7.0.3
3. Versi Database: 6.0.0

![image](https://github.com/eraporsmk/erapor7/assets/67053543/3f20cf5f-8539-4074-ad58-f4f598e7c833)
Sudah di input mapel pilihan...
![image](https://github.com/eraporsmk/erapor7/assets/67053543/1347f243-70db-45d5-a42a-d619f6236c5e)
Namun siswa dari lintas konsentrasi yg memilih matpel pilihan tidak muncul saat cetak Rapornya.. Diletakkan di nomor 11 Mapel Pilihannya...
Bagaimana yaaa??

**Comment by masadi** [comment]
wali kelas rombel pilihan harus sama dengan wali kelas rombel reguler
silahkan cek lagi wali kelasnya
