### ISSUE TITLE
KD dan CP Mapel Kejuruan bermasalah

### ISSUE THREAD

**Issue by yayanch** [eraporsmk/erapor7#47]
Sistem Operasi : Linux Ubuntu 20.04
Versi erapor : 7.0.3

Untuk mapel kejuruan TKJ :
https://github.com/eraporsmk/erapor7/assets/62583586/780a9ed7-b20b-4628-86e2-589f7bbea5d5
1. KD harus ditambah manual dan ketika mau dihapus tidak berhasil

https://github.com/eraporsmk/erapor7/assets/62583586/775761e2-48fc-4e07-93e8-05f87c50a462
2. CP harus diinput manual dan ketika sudah ditambah tidak muncul

**Comment by masadi** [comment]
Silahkan di perbaharui pak, sudah diperbaiki.
Khusus untuk hapus KD, memang tidak dalam arti menghapus/menghilangkan record dari database, tapi hanya mereset deskripsi KD menjadi bawaan aplikasi.

Terima Kasih
