### ISSUE TITLE
Gagal terkoneksi ke Web Services Dapodik

### ISSUE THREAD

**Issue by dendyms09** [eraporsmk/erapor7#48]
Aplikasi yang sedang dipakai:

Operating System dapo : windows11
Operating System erapor : windows10
Versi Aplikasi: 7.0.3
Versi Database: 6.0.0

![Screenshot_36](https://github.com/eraporsmk/erapor7/assets/101131862/ef2c0cc7-1a6f-4711-bac7-915201bd7381)

pengaturan web service di laptop dapo sudah ada token juga sudah di paste ke erapor yang ada di komputer server, namun muncul peringatan ini.

**Comment by WARDI-NURYANTO** [comment]
Bisa diphotokan lebih komplit pak langkahnya

**Comment by dendyms09** [comment]
Token sudah sesuai dengan servis dapodik
![Screenshot_47](https://github.com/eraporsmk/erapor7/assets/101131862/5324d6bb-d31e-4b68-a00d-9fa581757bd7)

sudah terkoneksi juga
![Screenshot_48](https://github.com/eraporsmk/erapor7/assets/101131862/7bbbbbc1-9eac-490d-ab8d-0ae9c4f098cf)

generate nilai mapel
![Screenshot_49](https://github.com/eraporsmk/erapor7/assets/101131862/7b461bfd-fdb8-419c-9d6e-fbcd576f3254)
![Screenshot_50](https://github.com/eraporsmk/erapor7/assets/101131862/946fa3b6-aa1b-4e07-8634-2518b9e2a47d)

namun gagal di akhir
![Screenshot_51](https://github.com/eraporsmk/erapor7/assets/101131862/4fe1107f-ee4c-4a1b-b050-8f15e2963d8b)

namun sebelumnya pengaturan token servis di dapo itu pakai localhost, ternyata harus pakai alamat ip erapor katanya. Nah tidak bisa diedit lagi pengaturan ip komputer dapo dan token web servicenya.
