### ISSUE TITLE
Menu NILAI PROYEK TIDAK ADA

### ISSUE THREAD

**Issue by agigohm** [eraporsmk/erapor7#49]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: 
2. Versi Aplikasi: 
3. Versi Database:
![image](https://github.com/eraporsmk/erapor7/assets/154298459/c517f6a9-4da4-43a3-8d69-23cc17243bff)

**Comment by WARDI-NURYANTO** [comment]
Atur Ulang Pengguna Pak dihak aksesnya, dishort Pilih Koord. P5 trusklik menu atur ukang pengguna

**Comment by agigohm** [comment]
![image](https://github.com/eraporsmk/erapor7/assets/154298459/3bb6b528-37fd-4ca6-bb47-b5cfd4cd1b1f)
tetep ga muncul pak

**Comment by WARDI-NURYANTO** [comment]
sudah klik atur ulang penggunanya
