### ISSUE TITLE
Hasil Sinkron Praktek Kerja Lapangan dari dapodik ke erapor7 bermasalah

### ISSUE THREAD

**Issue by alfanmuhammad262** [eraporsmk/erapor7#51]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai: e-Rapor SMK
1. Operating System: windows server 2019
2. Versi Aplikasi: 7.0.3
3. Versi Database: 6.0.0

Setelah sinkron dari dapodik untuk data DUDI:
1. Siswa-siswa yang berada di rombel yang berbeda (contoh XII TAB 1 dan XII TAB 2) namun dalam satu Industri tampil semua siswa-siswa tsb di semua rombel yang PKL di industri tsb.
![Halaman Penilaian PKL XII TAB 1 - INDOMARINE](https://github.com/eraporsmk/erapor7/assets/51165901/aa58a9c0-0349-4bbf-b615-0ce675ddc7af)
![Halaman Penilaian PKL XII TAB 2 - INDOMARINE](https://github.com/eraporsmk/erapor7/assets/51165901/5d70e2a6-1c5c-4079-8be9-bee5ea54a133)

Jika nilai diisikan di salah satu halaman penilaian rombel saja untuk siswa, maka cetak rapor PKL tidak muncul nilai. Sehingga siswa harus diberi nilai disemua halaman penilaian tiap rombel yang muncul nama siswa tsb, supaya cetak rapor PKL terisi nilai dan deskripsi.

2. Data siswa yang sudah lulus masuk menjadi anggota rombel PKL di dudi.
![Industri DUDI](https://github.com/eraporsmk/erapor7/assets/51165901/5f868fcc-11d8-4ed4-88c9-da0b5c81fe92)
![image](https://github.com/eraporsmk/erapor7/assets/51165901/b2b94bbe-5aa2-4d71-af7e-195eee4c22bd)

**Comment by ikydhana** [comment]
Silahkan dicob cek di bagian Perjanjian Kerjasama (PKS) di DAPODIK apakah masih ada siswa/i nya yang belum di keluarkan dari DUDI
