### ISSUE TITLE
TOMBOL MENU NILAI GENERATE TIDAK MNCUL, ADA SEBAGIAN MUNCUL

### ISSUE THREAD

**Issue by WARDI-NURYANTO** [eraporsmk/erapor7#53]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System:  Windows 10
2. Versi Aplikasi: 7.0.3
3. Versi Database: 6.0.0
![image](https://github.com/eraporsmk/erapor7/assets/119034175/77f939f4-e429-4507-8fc0-716d14ca523b)
 yang muncul ada seperti ini
![image](https://github.com/eraporsmk/erapor7/assets/119034175/441a00a1-b6be-432e-a02c-83e3b2b01cf1)

**Comment by masadi** [comment]
tombol generate nilai hanya tampil di pembelajaran yang memilik sub mapel
