### ISSUE TITLE
Data Rencana Penilaian P5 selalu muncul walaupun sudah dihapus

### ISSUE THREAD

**Issue by KangAbbie** [eraporsmk/erapor7#54]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: Windows 10
2. Versi Aplikasi: 7
3. Versi Database:7.03

Data Rencana Penilaian P5 selalu muncul walaupun sudah dihapus, Data lama masih teap ada muncul pada Cetak Rapor P5, harusnya hilang/kosong tanpa ada data penilaian P5. Jika ditambahkan Data Rencana Penilaian P5 yang baru data lama selalu ada.
![Perencanaan P5 View](https://github.com/eraporsmk/erapor7/assets/154737904/33487b14-ffaf-4973-b794-5f3f155e055e)

![Rapor P5 View](https://github.com/eraporsmk/erapor7/assets/154737904/669df34c-74ab-4f3b-a02f-4a01b3e5d615)

**Comment by masadi** [comment]
silahkan git pull, sementara di close dulu issue nya.
jika masih belum berhasil, silahkan open lagi
