### ISSUE TITLE
Terdapat Bug di Menu Nilai Dapodik

### ISSUE THREAD

**Issue by WARDI-NURYANTO** [eraporsmk/erapor7#6]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: Windows
2. Versi Aplikasi: 7.0.0
3. Versi Database: 6.0.0
Menu tampilkan semua tidak berfungsi, atau pindah ke sheet 2 data tidak berubah
![2023-09-27_14h22_41](https://github.com/eraporsmk/erapor7/assets/119034175/059a4648-fa46-4fe6-8880-cafae6c8583e)

**Comment by eraporsmk** [comment]
Silahkan update ke versi terbaru

Terima kasih
