### ISSUE TITLE
Status Kelulusan belum bisa disimpan

### ISSUE THREAD

**Issue by Kunyank** [eraporsmk/erapor7#63]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: win 10
2. Versi Aplikasi: 7.04
3. Versi Database:6.0.0
![image](https://github.com/eraporsmk/erapor7/assets/120827421/a8258d1d-194b-482d-9586-1ae32f386953)

**Comment by mutiaatmaja** [comment]
sama, kami juga

**Comment by masadi** [comment]
silahkan lakukan git pull
