### ISSUE TITLE
Request Fitur Delete Paket Penilaian UKK 

### ISSUE THREAD

**Issue by shinataputra** [eraporsmk/erapor7#64]
![image](https://github.com/eraporsmk/erapor7/assets/71615861/11e129d3-6b40-40f8-bb24-5a364486e192)

![image](https://github.com/eraporsmk/erapor7/assets/71615861/c47bcdaf-7eed-4e35-968a-c8626ff85e43)

**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: Win 11
2. Versi Aplikasi: 7.0.4
3. Versi Database: 6

muncul paket kompetensi ganda pada penilaian UKK meskipun sudah di nonaktifkan.

**Comment by masadi** [comment]
Sudah diperbaiki, silahkan lakukan git pull
