### ISSUE TITLE
Tidak bisa klik dropdown skala nilai PKL

### ISSUE THREAD

**Issue by dismanska** [eraporsmk/erapor7#67]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: Windows 10
2. Versi Aplikasi: 7.0.4
3. Versi Database: 6.0.0

Saat akan input skala nilai PKL, tidak bisa di klik menu dropdown nya. ini hanya terjadi di beberapa siswa saja, sisanya normal bisa di klik menu dropdown skala nilainya. mohon bantuan solusinya

![Screenshot 2024-04-05 124852](https://github.com/eraporsmk/erapor7/assets/120947091/9c38df35-3571-4b01-9801-db7f01352bbd)

**Comment by masadi** [comment]
Sudah diperbaiki, silahkan lakukan git pull
