### ISSUE TITLE
Tanda Tangan Mengetahui seharusnya Kepala Sekolah di aplikasi hanya Mengetahu kepala saja

### ISSUE THREAD

**Issue by Kunyank** [eraporsmk/erapor7#68]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai: 
1. Operating System: win 10
2. Versi Aplikasi: 7.0.4
3. Versi Database:6.0.0
![image](https://github.com/eraporsmk/erapor7/assets/120827421/9f3c39c8-961e-443a-ae29-b41209030331)

**Comment by masadi** [comment]
sudah di perbaharui
