### ISSUE TITLE
Jabatan Kepala Sekolah muncul sebagian (tanpa nama sekolah) dan Tanggal rapor kelas XII (kelas akhir) tidak sesuai

### ISSUE THREAD

**Issue by goesredy** [eraporsmk/erapor7#87]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: Windows 11
2. Versi Aplikasi: 7.0.4
3. Versi Database: 

Tanggal rapor yg muncul untuk kelas akhir adalah tanggal untuk kelas di bawahnya.
Nama jabatan hanya muncul nama "Kepala" tanpa nama sekolah
<img width="906" alt="Screen Shot 2024-05-21 at 17 28 50" src="https://github.com/eraporsmk/erapor7/assets/2682599/f5831b43-882a-4530-a348-1061848c7e13">
<img width="662" alt="Screen Shot 2024-05-21 at 17 29 40" src="https://github.com/eraporsmk/erapor7/assets/2682599/a905e90b-5484-40fd-b7cb-22d67323d79a">

**Comment by WARDI-NURYANTO** [comment]
**Berbagi Informasi**
Cari File 
C:\eRaporSMK\dataweb\resources\views\cetak

Untuk Jabatan di menu nilai 
pilih rapor_catatan.blade.php buka dengan _Notepad++_
**Pilih Baris  265**
<p>Mengetahui,<br>{{ get_setting('jabatan', $get_siswa->sekolah_id, $get_siswa->semester_id) }} </p>
diganti dengan
<p>Mengetahui,<br>{{ get_setting('jabatan', $get_siswa->sekolah_id, $get_siswa->semester_id) }} Tambahkan Nama Sekolah/ Sekolah,</p>

Untuk Jabatan di menu Identitas Sekolah samping Photo Siswa 
pilih identitas_peserta_didik.blade.php buka dengan Notepad++
**Pilih Baris  167**
<td style="width: 50%;padding:5px;">{{str_replace('Kab. ','',$get_siswa->peserta_didik->sekolah->kabupaten)}}, {{$get_siswa->peserta_didik->diterima}}<br />{{ get_setting('jabatan', $get_siswa->sekolah_id, $get_siswa->semester_id) }} </td>
diganti dengan
<td style="width: 50%;padding:5px;">{{str_replace('Kab. ','',$get_siswa->peserta_didik->sekolah->kabupaten)}}, {{$get_siswa->peserta_didik->diterima}}<br />{{ get_setting('jabatan', $get_siswa->sekolah_id, $get_siswa->semester_id) }} Tambahkan Nama Sekolah/ Sekolah,</td>

**Comment by WARDI-NURYANTO** [comment]
![image](https://github.com/eraporsmk/erapor7/assets/119034175/af722860-a2e4-417a-9ff0-a84740b9d85b)

Intinya mah menambahkan Nama Sekolah atau Sekolah saja

**Comment by masadi** [comment]
Sudah diperbaiki, silahkan git pull kemudian simpan ulang di pengaturan umum. Pastikan untuk memilih jabatan kepala sekolah yang sesuai.

Terima kasih
