### ISSUE TITLE
Pengaturan ulang akun PTK Semester Genap 2023/2024 bermasalah

### ISSUE THREAD

**Issue by alfanmuhammad262** [eraporsmk/erapor7#88]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai: e-Rapor SMK
1. Operating System: Windows Server 2019
2. Versi Aplikasi: 7.0.4
3. Versi Database: 6.0.0

Pengaturan ulang Akun PTK untuk Semester Genap hanya tergenaerate sebagian. Sedangkan Akun PTK Semester Ganjil aman ( Sehingga tidak berani melakukan Pengaturan ulang akun PTK yang semester ganjil ).

![image](https://github.com/eraporsmk/erapor7/assets/51165901/4cc29b2b-7eca-4d0f-97c1-d6451054d11b)

![image](https://github.com/eraporsmk/erapor7/assets/51165901/dbd35381-c299-4ddf-8e86-bdf8df7dc515)

**Comment by masadi** [comment]
Kapan terakhir kali melakukan git pull pak?

**Comment by alfanmuhammad262** [comment]
sekitar 30 April

**Comment by alfanmuhammad262** [comment]
Awal semua login aman, baru ketahuan setelah sinkron dari dapodik beberapa hari ini. ada laporan dari guru akun tidak memiliki akses.

**Comment by masadi** [comment]
Coba git pull dulu pak, nanti infokan hasilnya

Pada Sab, 25 Mei 2024, 16.59, alfanmuhammad262 ***@***.***>
menulis:

**Comment by alfanmuhammad262** [comment]
siap pak, kami coba dulu

**Comment by alfanmuhammad262** [comment]
masih sama pak

**Comment by alfanmuhammad262** [comment]
yang tercatat walas saja yang akun tergenerate

**Comment by masadi** [comment]
Baik, nanti malem remote
Hubungi salah satu HD dengan mengirim screenshot komentar saya


Pada Sab, 25 Mei 2024, 17.04, alfanmuhammad262 ***@***.***>
menulis:

**Comment by alfanmuhammad262** [comment]
iya pak

**Comment by masadi** [comment]
Yang masih bermasalah dengan atur ulang pengguna Guru, silahkan lakukan git clone ulang

**Comment by alfanmuhammad262** [comment]
setelah git clone masalah teratasi pak, termasuk masalah unduh legger. terima kasih.

**Comment by arifrahman26** [comment]
> Yang masih bermasalah dengan atur ulang pengguna Guru, silahkan lakukan git clone ulang

caranya bagaimana pak?
