### ISSUE TITLE
gagal php artisan erapor:update

### ISSUE THREAD

**Issue by adi21012** [eraporsmk/erapor7#9]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: debian 12 memakai aapanel 6.8.31
2. Versi Aplikasi: 6.0.5
3. Versi Database:14.2
4. ada problem seperti di gambar pak!!
![gambar](https://github.com/eraporsmk/erapor7/assets/146193753/44b3e1bd-1899-412a-b57c-3bd727e65d25)

**Comment by eraporsmk** [comment]
Silahkan menggunakan versi 7.
Untuk error seperti ini, di ulangi terus sampai tidak tampil error lagi. Karena mungkin database nya lama dan table migrations nya tidak mendeteksi ada file migrate baru.

**Comment by adi21012** [comment]
ini saya coba cari cara tetap tidak bisa baik ganti database ,permision user, ganti versi prostgresql ..di google juga tidak ada penyelesaian yang berkaitan dengan masalah ini

**Comment by eraporsmk** [comment]
Besok hubungi tim HD pak, agar dibantu remote

**Comment by adi21012** [comment]
bisa di bantu untuk kontaknya pak

**Comment by eraporsmk** [comment]
Silahkan kunjungi laman http://erapor.ditpsmk.net/faq
Kontak Helpdesk ada di bawah
