### ISSUE TITLE
Role Akun PTK tidak berubah pada sinkron selanjutnya.

### ISSUE THREAD

**Issue by goesredy** [eraporsmk/erapor7#90]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: Windows11
2. Versi Aplikasi: 7.0.4
3. Versi Database: 6.0.0

Pada sekolah kami, ada perubahan status guru, dari guru sebelumnya yang pindah tugas, kemudian digantikan oleh guru yang masih di sekolah.
Ada 2 role yang diganti, 1. Wali Kelas, 2. Pembina Ekstra.

Pada sisi admin, sudah tercantum guru pengganti.
Tapi pada akun guru pengganti, menu untuk role yang sesuai belum juga muncul.
Kemudian pada sisi admin dilakukan pengecekan, ternyata guru pengganti belum mendapat "role" sebagai wali kelas dan pembina ekstra.
Jadi mungkin saat pembaruan data dari dapodik, role/permission tidak ikut diperbaharui.

Terima kasih.

**Comment by masadi** [comment]
Silahkan atur ulang pengguna bapak

Pada Kam, 30 Mei 2024, 08.43, Ida Bagus Redy Santiawan <
***@***.***> menulis:

**Comment by goesredy** [comment]
Setelah "Atur Ulang Pengguna" (Akun PTK), data pengguna malah hilang pak, sisa hanya 1 akun.

**Comment by masadi** [comment]
git clone ulang coba pak, atau hubungi HD untuk minta bantuan agar di remote

**Comment by goesredy** [comment]
sudah pak, terima kasih
