### ISSUE TITLE
Erapor Tidak bisa di buka setelah menjalan perintah git pull

### ISSUE THREAD

**Issue by rachmandev** [eraporsmk/erapor7#91]
Erapor tidak bisa menampilkan data setelah menjalankan perintah git pull dan php artisan config:clear. jika klik oke selalu kembali dan tidak menampilkan data
![Screenshot from 2024-05-30 23-20-43](https://github.com/eraporsmk/erapor7/assets/46337752/46b2b1c1-6751-4250-af75-62e2d4b273a8)

Aplikasi yang sedang dipakai:
1. Operating System:  Ubuntu Server 24.04 LTS
2. Versi Aplikasi: 7.0.4
3. Versi Database: 6.0.0

**Comment by hid0** [comment]
hapus folder vendor
hapus file composer.lock

lalu jalankan lagi `git pull`
trs `composer update`
lalu terakhir `php artisan erapor:update`
