### ISSUE TITLE
Git for Windows has stopped

### ISSUE THREAD

**Issue by adhesck81** [eraporsmk/erapor7#92]
![Git for Windows has stopped working](https://github.com/eraporsmk/erapor7/assets/171541466/6c8a367d-1dea-43ff-b2f7-8f864752dc25)
Pada saat Git Pull tidak bisa, dan muncul notif "Git for Windows has stopped"
Aplikasi yang sedang dipakai:
1. Operating System: Win 10
2. Versi Aplikasi: 7.0.4
3. Versi Database: 6.0.0

**Comment by masadi** [comment]
Install ulang coba pak git windows nya
