### ISSUE TITLE
Tampilan detail nilai masih seperti versi lama (kolom pengetahuan dan keterampilan)

### ISSUE THREAD

**Issue by ndr-byHQ** [eraporsmk/erapor7#94]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Pada halaman beranda pengguna, detail nilai pada tiap-tiap mata pelajaran masih menampilkan kolom nilai pengetahuan dan keterampilan seperti pada erapor terdahulu. Sudah dilakukan git pull dan artisan update, tapi tetap seperti gambar dibawah.
Aplikasi yang sedang dipakai:
1. Operating System: Windows 11
2. Versi Aplikasi: 7.0.4
3. Versi Database: 6.0.2

![Screenshot_13](https://github.com/eraporsmk/erapor7/assets/171673953/ceb50f22-d351-4c6a-b5f3-fcde7477c38e)

**Comment by dwi-adhi-soegiarto** [comment]
apakah tampilan tersebut untuk walas yang masih menggunakan k13? karena kelas 12 di tempat saya masih menggunakan k13 dan tampilan di walas seperti itu, namun jika login menggunakan akun walas yang rombelnya menggunakan kumer tdk seperti itu

**Comment by ndr-byHQ** [comment]
Iya betul pak, hanya yg kurikulum k13 yg tampilannya seperti itu. Jenjang yg kurikulum merdeka sudah muncul deskripsi capaian kompetensinya

**Comment by masadi** [comment]
sudah diperbaiki, silahkan lakukan git pull

**Comment by ndr-byHQ** [comment]
Setelah dilakukan git pull tampilannya sudah berubah pak, tapi nilai akhirnya jadi tidak tampil.
Sudah saya cek melalui akun Guru dan Wali Kelas, di beranda ketika dipilih detail nilai, yg ditampilkan hanya update capaian kompetensinya saja, nilai akhirnya hilang (seperti di screenshot).  Tapi ketika diperiksa di menu nilai akhir (guru) dan menu ledger, serta ketika di cetak rapot, nilai akhir dan capaian kompetensinya muncul normal.
![WhatsApp Image 2024-06-07 at 09 02 01_f2a65222](https://github.com/eraporsmk/erapor7/assets/171673953/36eae077-1f27-4523-ac8e-06b8ad213b0f)

**Comment by masadi** [comment]
sudah di perbaiki pak, silahkan git pull lagi
