### ISSUE TITLE
GIT PULL ORIGIN MAIN ERAPOR 7 ERROR

### ISSUE THREAD

**Issue by WARDI-NURYANTO** [eraporsmk/erapor7#96]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: WINDOW 11
2. Versi Aplikasi: 7.0.4
3. Versi Database:6.0.0

![image](https://github.com/eraporsmk/erapor7/assets/119034175/a2de62c2-aece-4ff2-8287-55afc0d5259d)

Mohon solusinya

**Comment by goesredy** [comment]
ijin menjawab pak.

Itu mengartikan aplikasi tidak mendapat internet

**Comment by masadi** [comment]
cek lagi koneksi internetnya pak, bila perlu lakukan ping ke github.com di cmd lain
