### ISSUE TITLE
ERROR KIRIM DATA E-RAPOR

### ISSUE THREAD

**Issue by WARDI-NURYANTO** [eraporsmk/erapor7#97]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: Window 11
2. Versi Aplikasi: 7.0.4
3. Versi Database: 6.0.0
![image](https://github.com/eraporsmk/erapor7/assets/119034175/99d95696-8da1-41fd-83d2-866ebd13aa98)

Setelah git pull per tanggal 10 Juni 2024 pukul 10.00 WIB

**Comment by masadi** [comment]
Jalankan di cmd
git pull
composer update
php artisan erapor:update

Pada Sen, 10 Jun 2024, 12.29, ADMIN OPERATOR SEKOLAH <
***@***.***> menulis:

**Comment by WARDI-NURYANTO** [comment]
Terima Kasih, Mantappp sudah fix kembali

**Comment by masadi** [comment]
Referensi gelar bersumber dari dapodik. Jika di dapodik tersedia, di erapor
akan mengikuti

Pada Sen, 10 Jun 2024, 17.44, Ryan Hidayat ***@***.***>
menulis:
